name = "LatexLH"
uuid = "5ba6fdca-9616-4e1b-a942-77ddac530f53"
authors = ["hendri54 <hendricksl@protonmail.com>"]
version = "1.1"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
ArgCheck = "2"
DelimitedFiles = "1"
DocStringExtensions = "0.8, 0.9"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
